<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hindenburg | Katalog</title>
    <style>
        :root{font-family:Arial,sans-serif;color:#f2f2f2;background:#101010}*{box-sizing:border-box}body{margin:0;background:#101010}.hero{background:#050505;color:#fff;padding:34px clamp(20px,5vw,70px) 42px;border-bottom:1px solid #2b2b2b}.hero-inner,.catalog{max-width:1250px;margin:auto}.nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:48px}.brand{font-size:22px;font-weight:700;color:#fff}.nav a{color:#c7c7c7;text-decoration:none;margin-left:20px}.nav a:hover{color:#f0444d}.hero h1{font-size:clamp(32px,5vw,58px);max-width:680px;line-height:1.02;margin:0 0 14px}.hero p{color:#bdbdbd;font-size:17px;max-width:600px}.catalog{padding:36px 20px 60px}.catalog-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.catalog h2{font-size:27px;margin:0;color:#fff}.muted{color:#a6a6a6}.flash{max-width:1250px;margin:18px auto 0;padding:12px 15px;background:#183b25;color:#9ee2b0;border-radius:5px}.error{background:#45181b;color:#ff9da3}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.book{background:#181818;border:1px solid #303030;border-radius:9px;overflow:hidden;box-shadow:0 5px 18px #00000055}.cover{height:190px;background:#292929;display:flex;align-items:center;justify-content:center;overflow:hidden}.cover img{width:100%;height:100%;object-fit:cover}.cover span{font-size:46px;color:#c62832}.book-body{padding:18px}.book h3{margin:0 0 7px;font-size:20px;color:#fff}.meta{font-size:13px;color:#a6a6a6;margin:4px 0}.stock{margin:15px 0;font-weight:700;color:#67c98a}.out{color:#ff4b55!important}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:15px}.form-row select,.form-row input{min-width:0;border:1px solid #444;border-radius:5px;padding:9px;font:inherit;background:#101010;color:#f2f2f2}.form-row select:focus,.form-row input:focus{border-color:#c62832;outline:2px solid #c6283233}.button{border:0;border-radius:5px;padding:10px 12px;background:#c62832;color:#fff;cursor:pointer;font-weight:600}.button:hover{background:#e13a45}.button:disabled{background:#3b3b3b;color:#858585;cursor:not-allowed}.empty{padding:35px;background:#181818;border:1px dashed #555;border-radius:8px;text-align:center;color:#bdbdbd}@media(max-width:650px){.nav{align-items:flex-start;gap:14px;flex-direction:column;margin-bottom:32px}.nav a{margin:0 14px 0 0}.catalog-head{align-items:flex-start;flex-direction:column;gap:5px}}
    </style>
</head>
<body>
<header class="hero"><div class="hero-inner"><nav class="nav"><a class="brand" href="{{ route('home') }}">Hindenburg</a><div><a href="{{ route('members.index') }}">Member</a><a href="{{ route('buku.index') }}">Kelola buku</a><a href="{{ route('kategori-buku.index') }}">Genre</a></div></nav><h1>Unlimited Book Works.</h1><p>Setiap buku adalah sebuah Noble Phantasm. Pilih kisahmu untuk dipinjam atau dibeli.</p></div></header>
@if(session('success'))<div class="flash">{{ session('success') }}</div>@endif
@if($errors->any())<div class="flash error">{{ $errors->first() }}</div>@endif
<main class="catalog"><div class="catalog-head"><div><h2>Katalog buku</h2><div class="muted">{{ $bukus->count() }} judul tersedia</div></div></div>@if($bukus->isEmpty())<div class="empty">Belum ada buku di katalog.</div>@else<div class="grid">@foreach($bukus as $buku)<article class="book"><div class="cover">@if($buku->foto_buku)<img src="{{ asset('storage/'.$buku->foto_buku) }}" alt="{{ $buku->nama_buku }}">@else<span>▤</span>@endif</div><div class="book-body"><h3>{{ $buku->nama_buku }}</h3><p class="meta">{{ $buku->kategori?->nama_kategori ?? 'Tanpa genre' }} · ISBN {{ $buku->isbn }}</p><p class="stock {{ $buku->stok === 0 ? 'out' : '' }}">{{ $buku->stok === 0 ? 'Stok habis' : 'Stok: '.$buku->stok }}</p><form method="POST" action="{{ route('transaksi-buku.store') }}">@csrf<input type="hidden" name="buku_id" value="{{ $buku->id }}"><div class="form-row"><select name="member_id" required aria-label="Pilih member" {{ $buku->stok === 0 || $members->isEmpty() ? 'disabled' : '' }}><option value="">Pilih member</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->nama_member }}</option>@endforeach</select><input type="number" name="jumlah" min="1" max="{{ $buku->stok }}" value="1" required {{ $buku->stok === 0 || $members->isEmpty() ? 'disabled' : '' }}></div><div class="form-row"><button class="button" name="jenis" value="pinjam" {{ $buku->stok === 0 || $members->isEmpty() ? 'disabled' : '' }}>Pinjam</button><button class="button" name="jenis" value="beli" {{ $buku->stok === 0 || $members->isEmpty() ? 'disabled' : '' }}>Beli</button></div></form></div></article>@endforeach</div>@endif</main>
</body>
</html>
